[ubuntu_2404]
server1 ansible_host=10.10.10.11
server2 ansible_host=10.10.10.12

[ubuntu_2404:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/id_rsa   # adjust your key path
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
